blank_issues_enabled: true
contact_links:
  - name: Security policy
    url: https://github.com/tashev11/tashevnet/security/policy
    about: Please read this before reporting sensitive security issues.
